# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# _chad-paths.sh — single source of truth for chad-cron-wrapper file paths.
#
# Sourced by bash wrappers (chad-budget-audit, chad-mail-check, …) so the
# defaults aren't duplicated as string literals. Python wrappers
# (chad-premium-client) read the same env vars via os.environ.get with
# matching fallbacks; if you change a default here, also update its python
# fallback to keep them in lockstep.
#
# Deployed alongside the wrappers at /usr/local/share/chad/_chad-paths.sh
# by chad-setup.sh and sourced via:
#   . /usr/local/share/chad/_chad-paths.sh

# Single canonical task-profiles location.
export CHAD_PROFILES_FILE="${CHAD_PROFILES_FILE:-/usr/local/share/chad/task-profiles.json}"

# Premium call audit ledger (one JSON line per Anthropic call). Read by
# chad-budget-audit, written by chad-premium-client.
export CHAD_PREMIUM_AUDIT_FILE="${CHAD_PREMIUM_AUDIT_FILE:-/tmp/chad-premium.jsonl}"

# Feedback proposals (auto-generated by chad-budget-audit, latest first).
export CHAD_PROPOSALS_FILE="${CHAD_PROPOSALS_FILE:-/sandbox/.openclaw-data/memory/feedback-proposals.md}"

# Per-message AuthContext drop directory used by chad-email-check-cron and
# chad-issue-triage-cron when an inbound trigger authorizes premium escalation.
export CHAD_AUTH_CONTEXT_DIR="${CHAD_AUTH_CONTEXT_DIR:-/sandbox/.openclaw-data/state/auth-context-mail}"

# Mail-handled dedup ledger written by chad-mail-send and parsed by
# chad-email-check-cron.
export CHAD_MAIL_HANDLED_LOG="${CHAD_MAIL_HANDLED_LOG:-/sandbox/.openclaw/workspace/state/mail-handled.jsonl}"

# Sandbox credentials JSON (PROTON_*, ANTHROPIC_API_KEY).
export CHAD_CREDS_FILE="${CHAD_CREDS_FILE:-/sandbox/.nemoclaw/credentials.json}"

# Daily memory directory. Per-day human-readable journal lives in
# <CHAD_MEMORY_DIR>/<UTC-date>.md (created by chad-ensure-today-memory) and a
# parallel structured event log in <CHAD_MEMORY_DIR>/events-<UTC-date>.jsonl
# (appended by chad-log-event).
#
# WAS: /sandbox/.openclaw-data/memory — that path is for chad-self-improve
# artifacts (feedback-proposals.md), not the daily journal. The journal has
# always lived under /sandbox/.openclaw/workspace/memory; the prior default
# here was a stale value from before the sectioned-manifest restructure and
# nothing actually consumed it. Fixing so callers can rely on this constant.
export CHAD_MEMORY_DIR="${CHAD_MEMORY_DIR:-/sandbox/.openclaw/workspace/memory}"

# Structured event log for today (one JSON object per line). Resolved at
# call-time so cron jobs that span midnight always write to the right file.
chad_events_file_today() {
  printf '%s/events-%s.jsonl\n' "$CHAD_MEMORY_DIR" "$(date -u +%Y-%m-%d)"
}
